server:
  # 端口
  port: 8080
spring:
  application:
    # 应用名称
    name: eureka-server
eureka:
  instance:
    hostname: localhost
  client:
    # 该应用为注册中心，所以设置为 false，代表不向注册中心注册自己
    register-with-eureka: false
    # 由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以设置为 false
    fetch-registry: false
    #
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/